<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on win32)" generated="20210225 15:37:59.775" rpa="false">
<suite id="s1" name="Series" source="C:\Users\rjrodriguez\Documents\Rokub0\Clarovideo_Roku\RobotLibrary\Tests\VCardSeries\series.robot">
<test id="s1-t1" name="Reproducir_serie_con_inicio_sesion">
<kw name="Access and login" type="setup">
<msg timestamp="20210225 15:38:00.072" level="FAIL">No keyword with name 'Access and login' found. Did you mean:
    keywords.Access Login</msg>
<status status="FAIL" starttime="20210225 15:38:00.071" endtime="20210225 15:38:00.072"></status>
</kw>
<kw name="Logout Teardown" type="teardown">
<msg timestamp="20210225 15:38:00.074" level="FAIL">No keyword with name 'Logout Teardown' found.</msg>
<status status="FAIL" starttime="20210225 15:38:00.074" endtime="20210225 15:38:00.074">No keyword with name 'Logout Teardown' found.</status>
</kw>
<tags>
<tag>Critical</tag>
<tag>Incompleto</tag>
<tag>RutaCritica</tag>
</tags>
<status status="FAIL" starttime="20210225 15:38:00.069" endtime="20210225 15:38:00.075" critical="yes">Setup failed:
No keyword with name 'Access and login' found. Did you mean:
    keywords.Access Login

Also teardown failed:
No keyword with name 'Logout Teardown' found.</status>
</test>
<test id="s1-t2" name="Reproducir_serie_con_registro">
<kw name="Access and login" type="setup">
<msg timestamp="20210225 15:38:00.079" level="FAIL">No keyword with name 'Access and login' found. Did you mean:
    keywords.Access Login</msg>
<status status="FAIL" starttime="20210225 15:38:00.079" endtime="20210225 15:38:00.079"></status>
</kw>
<status status="FAIL" starttime="20210225 15:38:00.076" endtime="20210225 15:38:00.080" critical="yes">Setup failed:
No keyword with name 'Access and login' found. Did you mean:
    keywords.Access Login</status>
</test>
<doc>Suite Series</doc>
<status status="FAIL" starttime="20210225 15:37:59.777" endtime="20210225 15:38:00.083"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">Critical</stat>
<stat pass="0" fail="1">Incompleto</stat>
<stat pass="0" fail="1">RutaCritica</stat>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="Series">Series</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210225 15:38:00.040" level="ERROR">Error in file 'C:\Users\rjrodriguez\Documents\Rokub0\Clarovideo_Roku\RobotLibrary\Tests\VCardSeries\series.robot' on line 4: Initializing test library 'RobotLibrary' with arguments [ 192.168.0.200 | 20000 | 2000 | G:/GlobalHitss/Roku/QA/rokub0-qa/src/main.exe ] failed: FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "C:\Users\rjrodriguez\Documents\Rokub0\Clarovideo_Roku\RobotLibrary\Library\RobotLibrary.py", line 36, in __init__
    self._process = subprocess.Popen(path)
  File "c:\users\rjrodriguez\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\rjrodriguez\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,</msg>
</errors>
</robot>
